// // import {
// //   ClerkProvider
// // } from '@clerk/nextjs'

// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // import Header from '@/components/Header';
// // // import Footer from '@/components/Footer';
// // import Footer from '@/components/Footer';


// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <ClerkProvider>

// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
// //       >
// //         <Header />
// //         {children}
// //         <Footer />
// //       </body>
// //     </html>
// //     </ClerkProvider>
// //   );
// // }

// import { ClerkProvider } from '@clerk/nextjs'
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// import Header from '@/components/Header';
// import Footer from '@/components/Footer';

// import Script from "next/script";

// <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="beforeInteractive" />


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
//         >
//           <Header />
//           <main className="flex-grow">
//             {children}
//           </main>
//           <Footer />
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }

// import { ClerkProvider } from '@clerk/nextjs';
// import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
// import './globals.css';

// import Header from '@/components/Header';
// import Footer from '@/components/Footer';
// import Script from 'next/script';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// // ✅ Updated metadata
// export const metadata: Metadata = {
//   title: 'Invoicing App',
//   description: 'Easily manage and track your invoices with our invoicing app.',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <head>
//           {/* ✅ Razorpay script moved to <head> properly */}
//           <Script
//             src="https://checkout.razorpay.com/v1/checkout.js"
//             strategy="beforeInteractive"
//           />
//         </head>
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
//         >
//           <Header />
//           <main className="flex-grow">{children}</main>
//           <Footer />
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }


import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Enhanced metadata for SEO & Social Media previews
export const metadata: Metadata = {
  title: {
    default: "Invoicing App",
    template: "%s | Invoicing App",
  },
  description: "Easily manage and track your invoices with our invoicing app.",
  openGraph: {
    title: "Invoicing App",
    description: "Easily manage and track your invoices with our invoicing app.",
    url: "https://yourdomain.com", // Replace with your actual domain
    siteName: "Invoicing App",
    images: [
      {
        url: "/og-image.png", // Ensure you have this image in your public folder
        width: 1200,
        height: 630,
        alt: "Invoicing App Dashboard",
      },
    ],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Invoicing App",
    description: "Easily manage and track your invoices with our invoicing app.",
    images: ["/og-image.png"],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          {/* ✅ JSON-LD Structured Data for SEO */}
          <Script
            id="structured-data"
            type="application/ld+json"
            dangerouslySetInnerHTML={{
              __html: JSON.stringify({
                "@context": "https://schema.org",
                "@type": "WebApplication",
                name: "Invoicing App",
                url: "https://yourdomain.com",
                description: "Easily manage and track your invoices with our invoicing app.",
                image: "/og-image.png",
              }),
            }}
          />

          {/* ✅ Razorpay Script (Optimized Loading) */}
          <Script src="https://checkout.razorpay.com/v1/checkout.js" strategy="lazyOnload" />
        </head>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>
          <Header />
          <main className="flex-grow">{children}</main>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
